apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: kaniko
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Set up Docker Hub registrydd
        kind: deploy
        with:
          registry: https://index.docker.io/v1/
          username: cbpautomation
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: cloudbees-io/kaniko/.cloudbees/testing
        name: Push image to OCI registry
        with:
          destination: index.docker.io/cbpautomation/python-hello-world-docker:CORINNE-${{cloudbees.version}}
          labels: app=cbp
    needs:
      - Approval
  Approval:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 015d04e8-5bcb-11eb-93be-42010a83aee8
      disallowLaunchByUser: true
      instructions: ""
      approvalInputs: |
        {}
