apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "1.0.0"
          url: "docker.io/cbpautomation/python-hello-world-docker:1.0.0"
          digest: "XXX"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "1.0.0"
          digest: "XXX"
          url: "docker.io/cbpautomation/python-hello-world-docker:1.0.0"
          target-environment: "PREPROD"